services:
  bookingservice:
    build: .
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DB_PASSWORD=verysecretpassword
      - POSTGRES_DB=hotelbookings

    networks:
      - spring-postgres
    depends_on:
      db:
        condition: service_healthy
  db:
    image: postgres
    restart: always
    user: postgres
    secrets:
      - db-password
    environment:
      - POSTGRES_DB=hotelbookings
      - POSTGRES_PASSWORD_FILE=/run/secrets/db-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    networks:
      - spring-postgres
    expose:
      - 5432
    ports:
      - "5432:5432"

 
volumes:
  db-data:
secrets:
  db-password:
    file: db/password.txt
networks:
  spring-postgres:
