CREATE TABLE rooms
(
    room_id     INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_number VARCHAR(40) NOT NULL
);

CREATE TABLE reservations
(
    reservation_id BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    room_id        INTEGER,
    status         SMALLINT,
    start_date     DATE,
    end_date       DATE,
    created_at     DATE,
    FOREIGN KEY (room_id) REFERENCES rooms (room_id) ON DELETE SET NULL
);
